const SIZES = [{ label: '方形', dim: '1024 × 1024', active: true }, { label: '竖版', dim: '768 × 1024', active: false }, { label: '竖屏', dim: '720 × 1280', active: false }];
const MODELS = [{ label: '生成', value: 'wan2.7-image-pro', hint: '五图同步生成' }, { label: '理解', value: 'qwen3-vl-plus', hint: '构建商品画像' }, { label: '提示词', value: 'qwen3.7-max', hint: '设计平台化提示词' }, { label: '质检', value: 'qwen3-vl-plus', hint: '白底图规范复检' }];
const SPECS = [{ platform: 'Amazon', spec: '纯白底 · 主体 ≥85%' }, { platform: 'TikTok Shop', spec: '竖版 · 场景感' }, { platform: 'Temu', spec: '细节 · 卖点直给' }, { platform: 'Shopee', spec: '清晰 · 移动端优化' }];

export function RightPanel({ size, onSizeChange }: { size: string; onSizeChange: (size: string) => void }) {
  return <aside className="hidden w-[300px] shrink-0 overflow-y-auto border-l border-[#e2ddd5] bg-[#f8f5ef] px-5 py-7 xl:block"><div className="sticky top-0"><div className="eyebrow mb-2">Output setup</div><h2 className="text-xl font-semibold tracking-[-0.03em] text-[#17202b]">输出设置</h2><p className="mt-1 text-xs text-[#8d867c]">先定画幅，模型会按平台规范工作。</p>
    <div className="mt-7"><div className="mb-3 text-xs font-semibold text-[#514b43]">交付画幅</div><div className="space-y-2">{SIZES.map((s) => <button type="button" key={s.dim} onClick={() => onSizeChange(s.dim)} className={`flex w-full items-center justify-between rounded-xl border px-3.5 py-3 text-left transition ${size === s.dim ? 'border-[#ef6a4c] bg-[#fff1ed]' : 'border-[#e2ddd5] bg-[#fffdf9] hover:border-[#bbb2a6]'}`}><div className="flex items-center gap-2.5"><span className={`h-2 w-2 rounded-full ${size === s.dim ? 'bg-[#ef6a4c]' : 'bg-[#d9d3c9]'}`} /><span className={`text-sm font-semibold ${size === s.dim ? 'text-[#b84934]' : 'text-[#625b51]'}`}>{s.label}</span></div><span className="text-[11px] text-[#9a9389]">{s.dim}</span></button>)}</div></div>
    <div className="my-7 h-px bg-[#e2ddd5]" /><div><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold text-[#514b43]">这套图怎么完成</span><span className="text-[10px] font-semibold text-[#ef6a4c]">自动编排</span></div><div className="space-y-2">{MODELS.map((m) => <div key={m.label} className="flex items-center gap-3 rounded-xl bg-[#fffdf9] px-3.5 py-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#eee9e1] text-[10px] font-bold text-[#6b645b]">{m.label.slice(0, 1)}</span><div className="min-w-0"><div className="truncate text-xs font-semibold text-[#39342e]">{m.value}</div><div className="mt-0.5 text-[10px] text-[#9a9389]">{m.hint}</div></div></div>)}</div></div>
    <div className="my-7 h-px bg-[#e2ddd5]" /><div><div className="mb-3 text-xs font-semibold text-[#514b43]">平台速览</div><div className="space-y-2">{SPECS.map((p) => <div key={p.platform} className="flex items-center justify-between border-b border-[#e8e2d9] pb-2 text-xs"><span className="font-semibold text-[#4e4840]">{p.platform}</span><span className="text-right text-[10px] text-[#8d867c]">{p.spec}</span></div>)}</div></div>
    <div className="mt-7 rounded-2xl bg-[#19232b] px-4 py-4 text-xs leading-relaxed text-[#b6c0c5]"><span className="font-semibold text-[#fffaf3]">小模型先筛，强模型定稿。</span><br />批量质检用 flash，关键白底图交给 plus 精检。</div></div></aside>;
}
