const MODELS = [{ label: '画像', value: 'qwen3.7-max', hint: '商品画像与提示词基调' }, { label: '生成', value: 'wan2.7-image-pro', hint: '五图同步生成' }, { label: '编辑', value: 'qwen-image-2.0', hint: '本地化图生图替换' }];
const SPECS = [{ platform: 'Amazon', spec: '纯白底 · 主体 ≥85%' }, { platform: 'TikTok Shop', spec: '竖版 · 场景感' }, { platform: 'Temu', spec: '细节 · 卖点直给' }, { platform: 'Shopee', spec: '清晰 · 移动端优化' }];

export function RightPanel() {
  return <aside className="hidden w-[300px] shrink-0 overflow-y-auto border-l border-[#e2ddd5] bg-[#f8f5ef] px-5 py-7 xl:block"><div className="sticky top-0"><div className="eyebrow mb-2">Model router</div><h2 className="text-xl font-semibold tracking-[-0.03em] text-[#17202b]">模型编排</h2><p className="mt-1 text-xs text-[#8d867c]">三种能力统一走 Model Router，按流水线自动编排。</p>
    <div className="mt-7"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold text-[#514b43]">这套图怎么完成</span><span className="text-[10px] font-semibold text-[#ef6a4c]">自动编排</span></div><div className="space-y-2">{MODELS.map((m) => <div key={m.label} className="flex items-center gap-3 rounded-xl bg-[#fffdf9] px-3.5 py-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#eee9e1] text-[10px] font-bold text-[#6b645b]">{m.label.slice(0, 1)}</span><div className="min-w-0"><div className="truncate text-xs font-semibold text-[#39342e]">{m.value}</div><div className="mt-0.5 text-[10px] text-[#9a9389]">{m.hint}</div></div></div>)}</div></div>
    <div className="my-7 h-px bg-[#e2ddd5]" /><div><div className="mb-3 text-xs font-semibold text-[#514b43]">平台速览</div><div className="space-y-2">{SPECS.map((p) => <div key={p.platform} className="flex items-center justify-between border-b border-[#e8e2d9] pb-2 text-xs"><span className="font-semibold text-[#4e4840]">{p.platform}</span><span className="text-right text-[10px] text-[#8d867c]">{p.spec}</span></div>)}</div></div>
    <div className="mt-7 rounded-2xl bg-[#19232b] px-4 py-4 text-xs leading-relaxed text-[#b6c0c5]"><span className="font-semibold text-[#fffaf3]">文字建画像，图片按平台规范出。</span><br />五图同步生成，白底图附人工复检提醒，本地化走图生图编辑。</div></div></aside>;
}
