import { useState, type ChangeEvent, type FormEvent } from 'react';
import { PLATFORMS, type ImagePipelineInput } from '../types';

const SAMPLE = { productName: '轻量通勤托特包', sellingPoints: '防泼水面料、可装 15 寸笔记本、自重仅 380g、大容量多隔层', platforms: ['Amazon', 'TikTok Shop'] };

export function TaskForm({ loading, error, onSubmit }: { loading: boolean; error: string; onSubmit: (input: ImagePipelineInput) => void }) {
  const [productName, setProductName] = useState(''); const [sellingPoints, setSellingPoints] = useState(''); const [platforms, setPlatforms] = useState<string[]>(['Amazon']); const [detailTone, setDetailTone] = useState<ImagePipelineInput['detailTone']>('专业可信');
  const togglePlatform = (p: string) => setPlatforms((list) => list.includes(p) ? list.filter((x) => x !== p) : [...list, p]);
  const fillSample = () => { setProductName(SAMPLE.productName); setSellingPoints(SAMPLE.sellingPoints); setPlatforms(SAMPLE.platforms); };
  const ready = productName.trim() !== '' && sellingPoints.trim() !== '' && platforms.length > 0;
  function handleSubmit(e: FormEvent) { e.preventDefault(); if (!ready) return; onSubmit({ productName: productName.trim(), sellingPoints: sellingPoints.trim(), platforms, detailTone }); }

  return <form onSubmit={handleSubmit} className="mx-auto max-w-[880px] space-y-6">
    {error && <div className="rounded-xl border border-[#f0b7a8] bg-[#fff1ed] px-4 py-3 text-sm text-[#a44836]">{error}</div>}
    <section className="panel overflow-hidden"><div className="flex flex-col gap-4 border-b border-[#e9e3da] px-7 py-6 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow mb-2">先告诉我你要卖什么</div><h2 className="text-[26px] font-semibold tracking-[-0.04em] text-[#17202b]">商品信息</h2><p className="mt-1.5 max-w-xl text-sm leading-relaxed text-[#777168]">一句商品名，加上几条真实卖点，剩下的交给工作流。</p></div><button type="button" onClick={fillSample} className="self-start rounded-full border border-[#d9d3c9] px-3.5 py-2 text-xs font-semibold text-[#5e584f] transition hover:border-[#ef6a4c] hover:text-[#c84f36] sm:self-auto">填入示例</button></div>
      <div className="grid gap-6 px-7 py-7 md:grid-cols-[1fr_1fr]"><div><label className="mb-2 block text-xs font-semibold text-[#514b43]">商品名称 <span className="text-[#ef6a4c]">*</span></label><input className="field" value={productName} onChange={(e: ChangeEvent<HTMLInputElement>) => setProductName(e.target.value)} placeholder="例如：轻量通勤托特包" /></div><div><label className="mb-2 block text-xs font-semibold text-[#514b43]">核心卖点 <span className="text-[#ef6a4c]">*</span></label><textarea className="field min-h-[116px] resize-y" value={sellingPoints} onChange={(e: ChangeEvent<HTMLTextAreaElement>) => setSellingPoints(e.target.value)} placeholder="例如：防泼水、能装 15 寸电脑、380g 轻量" /><p className="mt-2 text-xs text-[#9a9389]">AI 会从文字信息建立商品画像，再驱动五图生成。</p></div></div>
    </section>
    <section className="panel px-7 py-7"><div className="eyebrow mb-2">选择你的销售场景</div><div className="flex flex-col gap-1.5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-[26px] font-semibold tracking-[-0.04em] text-[#17202b]">发布到哪里？</h2><p className="mt-1.5 text-sm text-[#777168]">首个平台会生成完整五图，其余平台自动适配主图。</p></div><span className="text-xs font-medium text-[#a49d92]">已选 {platforms.length} 个平台</span></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{PLATFORMS.map((p) => { const on = platforms.includes(p); return <button key={p} type="button" onClick={() => togglePlatform(p)} className={`rounded-2xl border px-4 py-4 text-left transition ${on ? 'border-[#ef6a4c] bg-[#fff1ed] text-[#b84934]' : 'border-[#e2ddd5] bg-[#fffdf9] text-[#6f685e] hover:border-[#bbb2a6]'}`}><span className={`mb-3 block h-2.5 w-2.5 rounded-full ${on ? 'bg-[#ef6a4c]' : 'bg-[#d9d3c9]'}`} /><span className="text-sm font-semibold">{p}</span><span className="mt-1 block text-[11px] text-[#9a9389]">{p === 'Amazon' ? '白底规范优先' : p === 'TikTok Shop' ? '竖版场景更吃香' : p === 'Temu' ? '卖点直给' : '移动端友好'}</span></button>; })}</div></section>
    <section className="panel px-7 py-6"><div className="eyebrow mb-2">DETAIL PAGE · 文案方向</div><div className="flex flex-col gap-1.5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-[22px] font-semibold tracking-[-0.035em] text-[#17202b]">详情页想怎么说？</h2><p className="mt-1.5 text-sm text-[#777168]">AI 会根据语气自动安排标题、卖点、场景、参数与 CTA。</p></div><span className="text-xs text-[#a49d92]">生成后可人工编辑</span></div><div className="mt-5 grid gap-2 sm:grid-cols-3">{(['专业可信', '种草转化', '简洁高端'] as const).map((tone) => <button key={tone} type="button" onClick={() => setDetailTone(tone)} className={`rounded-xl border px-3.5 py-3 text-left transition ${detailTone === tone ? 'border-[#ef6a4c] bg-[#fff1ed] text-[#b84934]' : 'border-[#e2ddd5] bg-[#fffdf9] text-[#6f685e] hover:border-[#bbb2a6]'}`}><span className="block text-sm font-semibold">{tone}</span><span className="mt-1 block text-[11px] text-[#9a9389]">{tone === '专业可信' ? '适合 Amazon / 品牌旗舰店' : tone === '种草转化' ? '适合 TikTok Shop / 社媒' : '适合高端、留白感品牌'}</span></button>)}</div></section>
    <div className="flex flex-col gap-4 border-t border-[#ddd6cc] pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-md text-xs leading-relaxed text-[#8d867c]">提交后将依次完成商品理解、五图生成、质检与详情页编排。你可以在“处理流程”中查看每一步。</p><button type="submit" disabled={loading || !ready} className="rounded-xl bg-[#ef6a4c] px-6 py-3.5 text-sm font-semibold text-white shadow-[0_10px_20px_rgba(239,106,76,.22)] transition hover:bg-[#d95d41] disabled:cursor-not-allowed disabled:bg-[#c9c1b7] disabled:shadow-none">{loading ? '正在生成图文详情页…' : '生成图片 + 详情页  →'}</button></div>
  </form>;
}
