/**
 * Image generation sub-Agent (core of this solution):
 * - Five image types generated by wan2.7-image-pro: white-background image / scene image / model image / comparison image / dimension diagram
 * - Image localization replacement (background / text / model image) uses the image editing model (async task)
 */
import { MODELS } from '../services/models.js';
import { modelRouter } from '../services/modelRouter.js';
import type { ImageType } from '../services/platformSpecs.js';

export interface GeneratedImage {
  type: ImageType;
  platform: string;
  size: string;
  url: string;
}

/** Generate a single image of the specified type */
export async function generateTypedImage(params: {
  type: ImageType;
  prompt: string;
  size: string;
  platform: string;
}): Promise<GeneratedImage | null> {
  const urls = await modelRouter.generateImage({
    model: MODELS.image.pro,
    prompt: params.prompt,
    size: params.size,
  });
  if (urls.length === 0) return null;
  return {
    type: params.type,
    platform: params.platform,
    size: params.size,
    url: urls[0],
  };
}

/**
 * Image localization: based on the original image, replace background scene / text language / model image,
 * matching the aesthetic preferences of different regional markets. Returns async task ID,
 * query the result via GET /api/tasks/:taskId.
 */
export async function localizeImage(params: {
  sourceUrl: string;
  targetMarket: string;
  instruction: string;
}): Promise<string> {
  return modelRouter.createImageTask({
    model: MODELS.image.edit,
    prompt: `Adapt this product image for the ${params.targetMarket} market: ${params.instruction}`,
    images: [params.sourceUrl],
  });
}
